### PR TITLE
Claim #23279 "Add unit tests for Taproot code in src/script/interpreter.cpp"

### PR DESCRIPTION
**Pull request by david-bakin**
Actually, since this is GitHub, I'll mark this draft for now.  When I get answers I'll either mark it ready for merge (or cancel it).

### CODE REVIEW

**Comment by david-bakin** [comment]
@blangel-nydig -  Help! `bitcoin@nydig.com` is locked down and won't accept emails from arbitrary people!

> Your message to [bitcoin@nydig.com](mailto:bitcoin@nydig.com) couldn't be delivered.
> The group bitcoin only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.
> david	Office 365	bitcoin
> Sender		Action Required
> Sender not allowed
>
> Original Message Details
> Created Date:	4/8/2022 6:24:44 PM
> Sender Address:	[david@bakins-bits.com](mailto:david@bakins-bits.com)
> Recipient Address:	[bitcoin@nydig.com](mailto:bitcoin@nydig.com)
> Subject:	Bounty program - specific questions re #23279 unit tests for taproot interpreter
> 
> Error Details
> Reported error:	550 5.7.133 RESOLVER.RST.SenderNotAuthenticatedForGroup; authentication required; Delivery restriction check failed because the sender was not authenticated when sending to this group
DSN generated by:	[PH0PR01MB6488.prod.exchangelabs.com](http://ph0pr01mb6488.prod.exchangelabs.com/)

**Comment by blangel-nydig** [comment]
@david-bakin 👀  on that.  I'll ping here when resolved and then you'll need to resend your email.

**Comment by blangel-nydig** [comment]
@david-bakin please try sending an email again to bitcoin@nydig.com

**Comment by david-bakin** [comment]
@blangel-nydig -  Fails now because one address of the group (or perhaps the forwarding address) is spelled wrong with domain `@nyidg.com` - I can provide full email address if you need but probably you'd prefer it not to be here.  Feel free to email me directly if you need it - address is above as "Sender Address:" ...

**Comment by blangel-nydig** [comment]
It came through.  We will respond to your great questions about the program!

**Comment by david-bakin** [comment]
I have a gitpod development environment set up now - at least for unit tests.  (I'll be making it public shortly, still some final touches on it.)  So I'm good to go on this task.  I'd still like information on using the already-set-up CI for running code coverage though.

**Review by blangel-nydig — APPROVED** [review]
Great! Excited to see you work on this.

**Pull request merged**
