### PR TITLE
Add link to PR for bip30 task

### PR DESCRIPTION
**Pull request by seejee**
Added a link to the PR that's awaiting review.

### CODE REVIEW

**Comment by blangel-nydig** [comment]
Great!  We'll help with an initial review.

**Comment by seejee** [comment]
hi @blangel-nydig! I have a single approval for my PR, but since then it's been a bit idle. I was wondering if you have any tips for getting more eyes on it. If not, I'll hop in the IRC and ask around. Thanks in advance!

**Comment by blangel-nydig** [comment]
Thanks @seejee .  I'll let @jamesob comment on the review process and best next steps for further reivew.

**Comment by jamesob** [comment]
Hi @seejee. Waiting for review is a classic difficulty with Core development - established contributors often wait weeks or longer to get sufficient review on their PRs. Sadly there isn't much that can be done here, other than (gently) making the case for why there's value in reviewing your PR on IRC or the original issue.

One good way of getting review on your PRs is to review others' PRs, if you have the time. Even if that just amounts to cloning the code locally, building, and running manual tests of some sort. There's a kind of informal "review credit" system, and if you review others' PRs they will more likely to pay attention to your work. This of course isn't perfect, but it's just the reality of how a distributed org like Bitcoin Core works.

**Comment by seejee** [comment]
Thanks for the tip @jamesob! I should have some time over the next few days to do some reviews/testing of other PRs (which will also be a great way for me to learn). Cheers!

**Comment by blangel-nydig** [comment]
@seejee saw that https://github.com/bitcoin/bitcoin/pull/24851#issuecomment-1277993620 was merged. Great job!

Please create a PR here to mark this task Completed and email [bitcoin@nydig.com](mailto:bitcoin@nydig.com) to start the process for payment.

**Pull request merged**
